version: "2.4"
services:
  spotifyd:
    image: ggoussard/spotifyd:latest
    restart: unless-stopped
    volumes:
      - /root/bathbuddy/config/spotifyd.conf:/etc/spotifyd.conf
      - /usr/share/alsa:/usr/share/alsa
    devices:
      - /dev/snd:/dev/snd
  bathbuddy:
    image: romulusai/bathbuddy:0.1
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - /root/bathbuddy/config/settings.cfg:/app/settings.cfg
      - /root/bathbuddy/config/.cache:/app/.cache
      - /var/run/docker.sock:/var/run/docker.sock:ro